// Parity: the rebuilt single core must reproduce the OLD app's trusted
// roster-page scores. For each capture in fixtures/captures/, the golden file
// (generated by the old extracted code via `npm run golden`) is the oracle; we
// run the rebuilt scoreCard on the same cards + same coeffs/calScales and assert
// every score matches.
//
// Run order:  npm run golden   (regenerate goldens from captures)  →  npm test

import { describe, it, expect } from "vitest";
import { readFileSync, readdirSync, existsSync } from "node:fs";
import { join } from "node:path";
import Papa from "papaparse";

import { scoreCard, computeDerived, type Coeffs, type CalScales } from "../src/scoring-core/index.ts";

const CARDS_CSV = "docs/pt_card_list.csv";
const CAPTURES_DIR = "fixtures/captures";
const GOLDEN_DIR = "fixtures/golden";

// Identical-expression ports should match to floating-point noise.
const TOL = 1e-9;

function loadCards(): any[] {
  const text = readFileSync(CARDS_CSV, "utf8");
  return Papa.parse(text, { header: true, skipEmptyLines: true }).data as any[];
}

interface Capture { label?: string; coeffs: Coeffs; calScales: CalScales | null }
interface GoldenRow {
  cardId: unknown; title: unknown;
  hit: Record<string, number>;
  pitch: Record<string, number>;
}
interface Golden { label: string; cardCount: number; rows: GoldenRow[] }

const goldenFiles = existsSync(GOLDEN_DIR)
  ? readdirSync(GOLDEN_DIR).filter((f) => f.endsWith(".golden.json"))
  : [];

if (goldenFiles.length === 0) {
  describe.skip("scoring-core parity (no goldens — run `npm run golden` after adding a capture)", () => {
    it("placeholder", () => {});
  });
} else {
  const cards = loadCards();

  for (const gf of goldenFiles) {
    const captureName = gf.replace(/\.golden\.json$/, ".json");
    const capturePath = join(CAPTURES_DIR, captureName);

    describe(`scoring-core parity — ${gf}`, () => {
      const golden = JSON.parse(readFileSync(join(GOLDEN_DIR, gf), "utf8")) as Golden;
      const capture = JSON.parse(readFileSync(capturePath, "utf8")) as Capture;
      const config = {
        coeffs: capture.coeffs,
        derived: computeDerived(capture.coeffs),
        calScales: capture.calScales,
      };

      it(`covers all ${golden.cardCount} cards in lockstep with the CSV`, () => {
        expect(golden.rows.length).toBe(cards.length);
      });

      it("reproduces every trusted hitting & pitching score", () => {
        let worst = 0;
        let worstWhere = "";
        let checked = 0;

        for (let i = 0; i < golden.rows.length; i++) {
          const g = golden.rows[i]!;
          const card = cards[i]!;
          // sanity: rows are aligned with the CSV order
          expect(String(card["Card ID"])).toBe(String(g.cardId));

          const s = scoreCard(card, config);
          const actual: Record<string, number> = {
            ...Object.fromEntries(Object.entries(s.hit).map(([k, v]) => [`hit.${k}`, v])),
            ...Object.fromEntries(Object.entries(s.pitch).map(([k, v]) => [`pitch.${k}`, v])),
          };
          const expected: Record<string, number> = {
            ...Object.fromEntries(Object.entries(g.hit).map(([k, v]) => [`hit.${k}`, v])),
            ...Object.fromEntries(Object.entries(g.pitch).map(([k, v]) => [`pitch.${k}`, v])),
          };

          for (const key of Object.keys(expected)) {
            const e = expected[key]!;
            const a = actual[key] ?? NaN;
            const diff = Math.abs(a - e);
            const allowed = TOL * (1 + Math.abs(e));
            checked++;
            if (diff > worst) { worst = diff; worstWhere = `${g.title} [${key}] expected=${e} actual=${a}`; }
            if (diff > allowed) {
              throw new Error(
                `Mismatch on card "${g.title}" (id ${g.cardId}) field ${key}: ` +
                `expected ${e}, got ${a} (diff ${diff} > ${allowed})`,
              );
            }
          }
        }
        // eslint-disable-next-line no-console
        console.log(`[parity ${golden.label}] ${checked} score checks; worst abs diff ${worst.toExponential(3)} (${worstWhere})`);
        expect(worst).toBeLessThanOrEqual(TOL * 10);
      });
    });
  }
}
